---
galaxy_info:
  author: Arne
  description: Aruba AOS-CX Switch Configuration Role
  company: Your Company
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: ArubaNetworks AOS-CX
      versions:
        - all
  galaxy_tags:
    - networking
    - aruba
    - aoscx
    - switching

dependencies: []