---
# Configure loopback L3 interfaces
# NOTE: Loopback interfaces are created in configure_l3_interfaces.yml before this is included.

- ansible.builtin.include_tasks:
    file: configure_l3_interface_common.yml
  vars:
    interface_list: "{{ l3_interfaces.loopback | selectattr('vrf', 'in', aoscx_builtin_vrfs + [none]) | list }}"
    interface_type: loopback
    vrf_type: default
  when: l3_interfaces.loopback | default([]) | length > 0

- ansible.builtin.include_tasks:
    file: configure_l3_interface_common.yml
  vars:
    interface_list: "{{ l3_interfaces.loopback | rejectattr('vrf', 'in', aoscx_builtin_vrfs + [none]) | list }}"
    interface_type: loopback
    vrf_type: custom
  when: l3_interfaces.loopback | default([]) | length > 0
