---
# Configure physical L3 interfaces

- ansible.builtin.include_tasks:
    file: configure_l3_interface_common.yml
  vars:
    interface_list: "{{ l3_interfaces.physical_default_vrf }}"
    interface_type: physical
    vrf_type: default
  when: l3_interfaces.physical_default_vrf | default([]) | length > 0

- ansible.builtin.include_tasks:
    file: configure_l3_interface_common.yml
  vars:
    interface_list: "{{ l3_interfaces.physical_custom_vrf }}"
    interface_type: physical
    vrf_type: custom
  when: l3_interfaces.physical_custom_vrf | default([]) | length > 0
