---
- name: Configure Aruba CX Switches
  hosts: all
  gather_facts: false

  roles:
    - role: aopdal.aruba_cx_switch
      vars:
        aoscx_idempotent_mode: true
        aoscx_configure_evpn: true
        aoscx_configure_vxlan: true
        aoscx_configure_ospf: true
        aoscx_configure_bgp: true
        aoscx_configure_vsx: true
        aoscx_rest_api_version: "10.16"
        aoscx_gather_facts_rest_api: true
