---
netbox_url: '{{ lookup("ansible.builtin.env", "NETBOX_API") }}'
netbox_token: '{{ lookup("ansible.builtin.env", "NETBOX_TOKEN") }}'
aoscx_rest_user: '{{ lookup("ansible.builtin.env", "ARUBA_USER") }}'
aoscx_rest_password: '{{ lookup("ansible.builtin.env", "ARUBA_PASSWORD") }}'
